name: GraalVM CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['23.0.2']
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache JVM
        id: cache-java
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.temp }}/java_package.tar.gz
            ~/.m2/repository
          key: ${{ runner.os }}-java-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-java-
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: '17'
          components: 'js'
      - name: Run tests (UNIX)
        run: ./mvnw clean verify
        if: runner.os != 'Windows'
      - name: Run tests (Windows)
        run: .\mvnw.cmd clean verify
        if: runner.os == 'Windows'
